# Generated by Django 5.0.1 on 2024-01-16 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taxconsultant',
            name='city',
            field=models.TextField(blank=True, max_length=20, null=True, verbose_name='City'),
        ),
    ]
