# Generated by Django 5.0.1 on 2024-01-17 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0002_alter_taxconsultant_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankaccount',
            name='IBAN',
            field=models.CharField(blank=True, max_length=60, null=True, unique=True, verbose_name='IBAN'),
        ),
    ]
