name: homie_core
services:

  homie_core:
    image: homie_core:1.0.0
    container_name: homie_core
    restart: unless-stopped
    ports:
      - "${LOCAL_HOST_PORT}:80"
    volumes:
      - ${ENTRYPOINT_LOCATION_PROD}:/web/app/entrypoint/start.sh
    environment:
      VIRTUAL_HOST: ${VIRTUAL_HOST}

  homie_core_q:
    image: homie_core:1.0.0
    depends_on: 
      - homie_core
    restart: unless-stopped
    volumes:
      - ${ENTRYPOINT_LOCATION_QCLUSTER}:/web/app/entrypoint/start.sh

networks:
  default:
    name: ${NETWORK_NAME}
    external: true